### ISSUE TITLE
 confuse mrmr_regression 

### ISSUE THREAD

**Issue by bvbvtw** [smazzanti/mrmr#21]
hi @smazzanti ,
I just find out this package in your Medium article, thank you for develope the mrmr package for slove the regression problem and the aritcle in Medium is brilliant,
I have a dataset, after one-hot encoding, there are 800 dummy features and my taget variable is continuous variable.
but what i confused is,it's allowed if i want to use **mrmr_regression** function for select the dummy features ?
I've read the code for **mrmr_regression** function , if my feature are categorical variables(in my case, is binary 0/1), these categorical variables will do the Pearson correlation with continuous variable(target) for calculate redundancy. 
I thought the Pearson correlation can only use between continuous - continuous.
Therefore, I'd like to check whether **mrmr_regression** can put the categorial variable for selection or not?
If can, do i need to modify the arguments for redundancy parameter? 

Thank you for taking the time to read my issue, and hopefully you would give me some advise.

**Comment by smazzanti** [comment]
Hi @bvbvtw, yes you can use it with **mrmr_regression**, and optionally you can pass the list of categorical features with the argument **cat_features**.
