### ISSUE TITLE
ModuleNotFoundError: No module named 'polars'

### ISSUE THREAD

**Issue by gorj-tessella** [smazzanti/mrmr#28]
On attempting to import received the following error: ModuleNotFoundError: No module named 'polars'

I believe the polars module needs to be added to setup.py.

**Comment by ZenithClown** [comment]
From what I have read, `polars` is not a dependency for `mrmr` but can work with a `polars`. So maybe, you need to install the module to your environment and try it again.

**Comment by smazzanti** [comment]
I have added Polars in the requirements of version 0.2.8
