### ISSUE TITLE
Ability to Select Least Important Features

### ISSUE THREAD

**Issue by jdholtz** [smazzanti/mrmr#30]
Thanks for making this great package! I have a small feature request which is to be able to select the least important features instead of the most important features using MRMR. I may be misunderstanding MRMR and it may not be able to be used for this. Would it be as simple as changing `argmax` to `argmin` on line 134 of main.py to get the least important features?

**Comment by smazzanti** [comment]
Yes, that's correct, by using argmin instead of argmax, you will select the feature that is minimally relevant and maximally redundant.
Thanks for your message!
