### ISSUE TITLE
Method

### ISSUE THREAD

**Issue by seymatakir28** [smazzanti/mrmr#31]
Which methods were used to assess relevance and redundancy, such as Random Forest, Mutual Information, or others?

**Comment by smazzanti** [comment]
They are specified in the function docstring. For instance:
relevance -> "f" (f-statistic), "ks" (kolmogorov-smirnov), "rf" (random forest).
redundancy -> "c" (Pearson correlation).
You can also pass a callable to define your own relevance/redundancy.

**Comment by seymatakir28** [comment]
So, if I don't customize it, which one does it use by default?

**Comment by smazzanti** [comment]
"f" for relevance and "c" for redundancy
