### ISSUE TITLE
Final Score

### ISSUE THREAD

**Issue by seymatakir28** [smazzanti/mrmr#34]
Is it possible to additionally return the final score used for sorting? I would like to make the number of features actually used dependent on a threshold on this score. Or is there a simple formula so that I can calculate this using redundancy and relevance?

**Comment by xyaxxa** [comment]
hi, have you solved this issue? I face the same problem too. thank you~

**Comment by seymatakir28** [comment]
hi, yes. you should add 'return_scores = True'.
