### ISSUE TITLE
Order of selected features

### ISSUE THREAD

**Issue by jhazart** [smazzanti/mrmr#37]
Hi,
it seems that selected features are not ordered by relevance :

selected_features, relevance, redundacy  = outputs_from_mrmr
print(relevance.values[selected_features[0:5]])
[77.04191317  7.65999306  2.1369512  71.32355801 44.90570244]

Is it a bug or the user is supposed to sort the values to get the decreasing curve of features relevance ?
Or maybe I missed something ?

Thanks a lot

**Comment by NJTechMXY** [comment]
This package is not in maintenance?

**Comment by xyaxxa** [comment]
mRMR includes relevance and redundancy, it doesn't only depend on the relevance，redundancy is also a indicator in sorting

**Comment by smazzanti** [comment]
As @xyaxxa said, the purpose of MRMR is to jointly maximize relevance and minimize redundancy, so the top features are not necessarily the ones with highest relevance
