### ISSUE TITLE
Spearman correlation for redundancy

### ISSUE THREAD

**Issue by antoniotdelend** [smazzanti/mrmr#42]
How can i implement Spearman correlation coefficient to calculate redundancy? There's any way this could be done using spearmanr from scipy?

link bellow:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.spearmanr.html

**Comment by smazzanti** [comment]
You can pass a callable as specified here:

    redundancy: str or callable
        Redundancy method.
        If string, name of method, supported: "c" (Pearson correlation).
        If callable, it should take "X", "target_column" and "features" as input and return a pandas.Series
        containing a score of redundancy for each feature.
