### ISSUE TITLE
mRMR Access - License

### ISSUE THREAD

**Issue by karthikm15** [smazzanti/mrmr#6]
@smazzanti, thank you for your clearcut explanations in your Medium articles and in your documentation on Github. I'm excited to see this package grow even further in the coming years.

I was wondering if you could add a license to the Github README.md, just for some additional clarification on the permissions that are available with the mRMR library. I would like to use and potentially modify parts of this code.

Let me know as soon as possible. Thanks!

**Comment by smazzanti** [comment]
Hi @karthikm15, thank you for your interest! I've just added a LICENSE.md, hope this helps.
